name: CI
on: [push, pull_request]
defaults:
  run:
    shell: bash
env:
  OPENRCT2_BUILD_SERVER: GitHub
  OPENRCT2_ORG_TOKEN: ${{ secrets.OPENRCT2_ORG_TOKEN }}
  BACKTRACE_IO_TOKEN: ${{ secrets.BACKTRACE_IO_TOKEN }}
  OPENRCT2_VERSION: 0.3.5.1
jobs:
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    container:
      image: openrct2/openrct2-build:4-format
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run clang-format
        shell: sh
        run: scripts/check-code-formatting
  android:
    name: Android
    runs-on: ubuntu-latest
    needs: check-code-formatting
    container:
      image: openrct2/openrct2-build:0.3.1-android
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          key: android
      - name: Build OpenRCT2
        run: |
          . scripts/setenv
          pushd src/openrct2-android
            ./gradlew app:assemblePR
          popd
          mkdir -p artifacts
          mv src/openrct2-android/app/build/outputs/apk/arm/pr/app-arm-pr.apk artifacts/openrct2-arm.apk
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v2
        with:
          name: OpenRCT2-Android
          path: artifacts
          if-no-files-found: error
      - name: Upload artifacts (openrct2.org)
        run: |
          . scripts/setenv -q
          if [[ "$OPENRCT2_PUSH" == "true" ]]; then
              upload-build artifacts/openrct2-arm.apk android-arm $OPENRCT2_VERSION $OPENRCT2_SHA1 $OPENRCT2_BRANCH
          else
              echo 'Not going to push build'
          fi
