name: CI
on: [push, pull_request]
env:
  OPENRCT2_BUILD_SERVER: GitHub
  OPENRCT2_ORG_TOKEN: ${{ secrets.OPENRCT2_ORG_TOKEN }}
  BACKTRACE_IO_TOKEN: ${{ secrets.BACKTRACE_IO_TOKEN }}
  OPENRCT2_VERSION: 0.2.6
jobs:
  lint-commit:
    name: Lint Commit Message
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v1
        with:
          configFile: .commitlint.json
  check-code-formatting:
    name: Check code formatting
    runs-on: ubuntu-latest
    container:
      image: openrct2/openrct2-build:0.2.4-format
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run clang-format
        run: scripts/check-code-formatting
  windows:
    name: Windows
    runs-on: windows-latest
    needs: [lint-commit, check-code-formatting]
    if: needs.lint-commit.result == 'success' && needs.check-code-formatting.result == 'success'
    strategy:
      fail-fast: false
      matrix:
        platform: [win32, x64]
    env:
      CONFIGURATION: Release
      PLATFORM: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build OpenRCT2
        shell: bash
        run: . scripts/setenv && build
      - name: Build artifacts
        shell: bash
        run: |
          . scripts/setenv -q
          build-portable
          build-symbols
          build-installer -i
      - name: Upload artifacts (CI)
        uses: actions/upload-artifact@v2-preview
        with:
          name: "OpenRCT2-Windows-${{ matrix.platform }}"
          path: artifacts/*
      - name: Run Tests
        shell: bash
        run: . scripts/setenv -q && run-tests
      - name: Upload artifacts (openrct2.org)
        shell: bash
        run: |
          . scripts/setenv -q
          if [[ "$OPENRCT2_PUSH" == "true" ]]; then
              upload-build artifacts/openrct2-portable-*.zip "windows-portable-$PLATFORM" $OPENRCT2_VERSION $OPENRCT2_SHA1 $OPENRCT2_BRANCH
              upload-build artifacts/openrct2-installer-*.exe "windows-installer-$PLATFORM" $OPENRCT2_VERSION $OPENRCT2_SHA1 $OPENRCT2_BRANCH
              upload-build artifacts/openrct2-symbols-*.zip "windows-symbols-$PLATFORM" $OPENRCT2_VERSION $OPENRCT2_SHA1 $OPENRCT2_BRANCH
              upload-backtrace-symbols artifacts/openrct2-symbols-*.zip
          else
              echo 'Not going to push build'
          fi
