name: 'Manage stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          days-before-pr-stale: 14
          days-before-pr-close: 14
          stale-pr-label: 'stale-pr'
          stale-pr-message: 'This PR is stale because it has been open for 14 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-pr-message: 'This PR was closed because of no activity.'
