name: 'Manage stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v7
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 1
          only-issue-labels: 'backtrace.io'
          stale-issue-label: 'stale-backtrace'
          stale-pr-message: 'This issue is stale because it has been open for 60 days with no activity. Remove stale label or comment or this will be closed tomorrow.'
          close-pr-message: 'This issue was closed because of no activity.'
